config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :users
  
  get 'login',    to: 'sessions#new'
  post 'login',   to: 'sessions#create'
  post 'logout',  to: 'sessions#destroy'
  get 'welcome',  to: 'sessions#welcome'

  post 'confirm_attendance',    to: 'event_attendances#create'
  delete 'cancel_attendance', to: 'event_attendances#destroy'

  root 'sessions#welcome'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :description, :date

  belongs_to :creator, class_name: 'User'
  has_many :event_attendances, foreign_key: 'attended_event_id', dependent: :destroy
  has_many :attendees, through: 'event_attendances', source: 'attendee', class_name: 'User', foreign_key: 'user_id'

  scope :past, -> { where('date < ?', Time.current).order('date DESC') }
  scope :future, -> { where('date >= ?', Time.current).order('date ASC') }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name

  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event', dependent: :destroy
  has_many :event_attendances, foreign_key: 'attendee_id', dependent: :destroy
  has_many :attended_events, foreign_key: 'attendee_id', through: 'event_attendances', class_name: 'Event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Make the methods defined here avalilable to the views
  helper_method :current_user
  helper_method :logged_in?

  # Who is the current user?
  def current_user
    User.find_by(id: session[:user_id])
  end

  # Is there a user logged in?
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  before_action :set_attended_event

  # POST /events/1
  # attended_event_id | attendee_id
  def create
    @attended_event = EventAttendance.new(event_params)

    respond_to do |format|
      if @attended_event.save
        format.html do
          redirect_to event_url(event_params[:attended_event_id]),
                      notice: 'Event attendance was successfully confirmed.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  def destroy
    EventAttendance.find_by(attended_event_id: event_params[:attended_event_id]).destroy
    respond_to do |format|
      format.html do
        redirect_to event_url(event_params[:attended_event_id]), notice: 'Event attendance was successfully cancelled.'
      end
    end
  end

  private

  # Set @attended_event
  def set_attended_event
    @attended_event = Event.find(event_params[:attended_event_id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event_attendance).permit(:attended_event_id, :attendee_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
    @event_attendance = EventAttendance.new # Allow atendee (User) to attend from the Event's show page
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  def create
    unless current_user
      redirect_to login_path, notice: 'You need to be logged in to create an event.'
      return
    end
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /welcome
  def welcome; end

  # GET /login
  def new
    render :login
  end

  # POST /login
  def create
    user = User.find_by(name: params[:name])

    if user
      session[:user_id] = user.id
      redirect_to user
    else
      redirect_to new_user_url, notice: 'User not found! Sign up, first.'
    end
  end

  # POST /logout
  def destroy
    reset_session
    redirect_to welcome_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    @users = User.all.order(:name)
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        session[:user_id] = @user.id # Stores user_id in a session
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  def destroy
    reset_session if @user == current_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendances/_form.html.erb
<%= form_with(model: event_attendance) do |form| %>
  <% if event_attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_attendance.errors.count, "error") %> prohibited this event attendance from being saved:</h2>

      <ul>
        <% event_attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%#= form.label :description, class: 'form-label' %>
    <%= form.number_field :attended_event_id, value: @event.id, class: 'form-control'%>
  </div>

  <div class="field form-group">
    <%#= form.label :date, class: 'form-label' %>
    <%= form.number_field :attendee_id, value: current_user.id, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Attend this Event',class: 'btn btn-lg btn-success'%>
  </div>

<% end %>

<%#= link_to 'Attend this Event', edit_event_path(@event), class: 'btn btn-lg btn-success' %>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_field :description, class: 'form-control', required: true %>
  </div>

  <div class="field form-group mb-3">
    <%= form.label :date, class: 'form-label' %>
    <%= form.datetime_select :date, type: 'datetime-local', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success mb-3'%>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event, class: 'btn btn-success mb-3' %>
<%= link_to 'Back', events_path, class: 'btn btn-success mb-3' %>

app/views/events/index.html.erb
<h1 class="text-white bg-success p-2" >Events</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col" colspan="3"><h2 class="text-success">Upcoming</h2></th>
    </tr>
  </thead>
  <tbody>
    <% @events.future.each do |event| %>
      <tr>
        <th class= "fs-4 link-success text-decoration-none" scope="row"><%= link_to event.description, event, class: 'fs-4 link-success text-decoration-none' %></th>
        <td class= "fs-4"><%= event.date.strftime("%A %b %d, %Y \t\t %H:%M") %></td>
        <td class= "fs-4 link-dark text-decoration-none"><%= link_to event.creator.name, user_path(event.creator.id), class: 'fs-4 link-dark text-decoration-none' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<table class="table">
  <thead>
    <tr>
      <th c scope="col" colspan="3"><h2 class="text-secondary">Past</h2></th>
    </tr>
  </thead>
  <tbody>
    <% @events.past.each do |event| %>
      <tr>
        <th class= "fs-4 link-success text-decoration-none" scope="row"><%= link_to event.description, event, class: 'fs-4 link-secondary text-decoration-none' %></th>
        <td class= "fs-4"><%= event.date.strftime("%A %b %d, %Y \t\t %H:%M") %></td>
        <td class= "fs-4 link-dark text-decoration-none"><%= link_to event.creator.name, user_path(event.creator.id), class: 'fs-4 link-dark text-decoration-none' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Event', new_event_path, class: 'btn btn-success mb-3' if current_user %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path, class: 'btn btn-outline-success mb-3' %>

app/views/events/show.html.erb
<h1 class="text-success"><%= @event.description %></h1>
<br>
<p class="text-success h6">When: <span class="fw-bold"><%= @event.date.strftime("%^A %b %d, %Y") %></span></p>
<p class="text-success h6">Creator: <span class="fw-bold"><%= @event.creator.name %></span></p>
<br>

<!-- ATTENDANCE FORM BEGIN -->
<%= form_with(model: @event_attendance, url: "/confirm_attendance", method: :post) do |form| %>
  <% if @event_attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_attendance.errors.count, "error") %> prohibited this event attendance from being saved:</h2>

      <ul>
        <% @event_attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group visually-hidden">
    <%= form.number_field :attended_event_id, value: @event.id, class: 'form-control'%>
  </div>

  <div class="field form-group visually-hidden">
    <%= form.number_field :attendee_id, value: current_user.id, class: 'form-control' if current_user %>
  </div>

  <div class="actions">
    <%= form.submit 'Attend this Event',class: 'btn btn-success' if current_user %>
  </div>

<% end %>
<!-- ATTENDANCE FORM END -->

<br>
<br>
<ul class="list-group">
  <li class="list-group-item active" aria-current="true">Attendees</li>

  <%= form_with(model: @event_attendance, url: "/cancel_attendance", method: :delete) do |form| %>
    <%= form.number_field :attended_event_id, value: @event.id, class: 'form-control visually-hidden'%>
    <%= form.number_field :attendee_id, value: current_user.id, class: 'form-control visually-hidden' if current_user %>

    <% @event.attendees.each do |attendee| %>
      <li class="list-group-item d-flex justify-content-between">
        <span><%= attendee.name %></span>
        <span><%= form.submit 'Cancel Attendance', class: 'btn btn-sm btn-outline-danger' if current_user == attendee%></span>
      </li>
    <% end %>
  <% end %>
</ul>
<br>
<hr>
<%= link_to 'Back', events_path, class: 'btn btn-outline-success mb-3' %>
<%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-outline-success mb-3' if current_user == @event.creator %>
<%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mb-3' if current_user == @event.creator %></td>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold" href="/">PRIVATE EVENTS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "Events", events_path, class: 'nav-link'%>
        </li>

        <li class="nav-item">
          <%= link_to "Users", users_path, class: 'nav-link'%>
        </li>

      </ul>
      <span class="d-flex">
        <% if logged_in? %>
            <%= link_to current_user.name, user_path(current_user.id), class: 'nav-link fw-bold text-primary' %>
            <%= link_to "Log out", logout_path, method: :post, class: 'btn btn-outline-dark'%>
        <% else %>
          <%= link_to "Join", welcome_path, class: 'btn btn-outline-dark'%>
        <% end %>
      </span>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Private Events</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-primary" >Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, class: 'btn btn-outline-primary my-3' %>
<%= link_to 'Back', users_path, class: 'btn btn-outline-primary my-3' %>

app/views/users/index.html.erb
<h1 class="text-white bg-primary p-2" >Users</h1>

<table class="table">
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= link_to user.name, user, class: 'fs-4 link-primary text-decoration-none' %></th>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<h1 class="text-primary" >Sign up</h1>

<%= render 'form', user: @user %>
<br>
<hr>
<br>
<h3 class="text-primary">Already registered?</h3>
<p class="text-primary">Log in, instead.</p>
<%= link_to "Log in", login_path, method: :get, class: 'btn btn-outline-primary' %>

<%= link_to 'Back', users_path, class: 'btn btn-outline-primary my-3' %>

app/views/users/show.html.erb
<h1 class="text-primary"><%= @user.name %></h1>
<br>
<div class="row row-cols-1 row-cols-lg-3 g-4">
    <ul class="list-group">
      <li class="list-group-item active" aria-current="true">Created</li>
      <% @user.created_events.each do |event| %>
        <li class="d-flex justify-content-between list-group-item">
          <span><%= event.description %></span>
          <span>
            <span class="badge bg-primary rounded-pill"><%= event.date.strftime("%^A %b %d, %Y") %></span>
            <span class="badge bg-primary rounded-pill"><%= event.date.strftime("%H:%M") %></span>
          </span>
        </li>
      <% end %>
    </ul>
    <ul class="list-group">
      <li class="list-group-item active" aria-current="true">Upcoming events</li>
      <% @user.attended_events.each do |event| %>
        <% if event.date >= Time.current %>
          <li class="d-flex justify-content-between list-group-item">
            <span><%= event.description %></span>
            <span>
              <span class="badge bg-primary rounded-pill"><%= event.date.strftime("%^A %b %d, %Y") %></span>
              <span class="badge bg-primary rounded-pill"><%= event.date.strftime("%H:%M") %></span>
            </span>
          </li>
        <% end %>
      <% end %>
    </ul>
    <ul class="list-group">
      <li class="list-group-item list-group-item-dark" aria-current="true">Previously attended events</li>
      <% @user.attended_events.each do |event| %>
        <% if event.date < Time.current %>
          <li class="d-flex justify-content-between list-group-item">
            <span><%= event.description %></span>
            <span>
              <span class="badge bg-secondary rounded-pill"><%= event.date.strftime("%^A %b %d, %Y") %></span>
              <span class="badge bg-secondary rounded-pill"><%= event.date.strftime("%H:%M") %></span>
            </span>
          </li>
        <% end %>
      <% end %>
    </ul>
</div>
<br>
<hr>
<%= link_to 'Back', users_path, class: 'btn btn-outline-primary my-3' %>
<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-outline-primary my-3'if current_user == @user %>
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger my-3' if current_user == @user %></td>